#!/bin/sh

IMG=/tmp/otb.img

case "$1" in
        http*.gz) curl "$1" ;;
        .) cat "overthebox/source/bin/targets/x86/64/overthebox-"*"-x86-64-combined-squashfs.img.gz" ;;
        *) curl "http://downloads.overthebox.net/${1:-develop}/targets/x86/64/latest.img.gz" ;;
esac | gunzip -c > "$IMG"

qemu-system-x86_64 -enable-kvm -cpu host  -m 1G \
        -drive "format=raw,file=$IMG,snapshot=on" \
        -nographic -netdev tap,id=br-lan,ifname=tap0,script=/root/angt/bash-1,downscript=no -device e1000,netdev=br-lan  -netdev tap,id=wan,ifname=tap1,script=/root/angt/bash-2,downscript=no -device e1000,netdev=wan

#bash /root/angt/bash-up
